### ISSUE TITLE
Split Mocks

### ISSUE THREAD

**Issue by jguffey** [avdg/screeps#48]
I noticed that you have more [Screeps mocks](https://github.com/avdg/screeps/tree/master/lib/mocks) than anywhere else I've been able to find. Would you be ok with splitting your mocks into a separate and open-source lib? Ideally, hosted as an npm module? I've mocked `Creep`, but I'm just starting screeps and have been considering publishing a mock lib for other players to use.

If you are ok with it, I could help, at least by merging in my creep mock, and helping mock out more objects and methods of the game.

**Comment by avdg** [comment]
Sorry, I do not maintain this project anymore. By now I believe there is some public code out and at the time when this repository maintained, lots of code where maintained by copying documentation or scraping few js files from the screeps website.

From a maintenance standpoint, the api is quite large and quite challenging to maintain. So for testability you tend to be better off using as less api code (eventually using an adapter or something, though giving the api also does a lot of logics for consuming code instead of only communicating with the screeps server probably not worth?) as possible to avoid issues with changing api's and avoiding testability issues due to not having screeps code available in testing environment.
